service: journal
image: mblayman/journal

servers:
  web:
    hosts:
      - 178.128.132.8
    proxy:
      app_port: 8000
      host: journeyinbox.com
      ssl: true
      healthcheck:
        # The db migration might make the app take longer to boot up
        # so provide more time before failing the health check.
        timeout: 60
    cmd:
      /app/app

registry:
  username: mblayman
  password:
    - KAMAL_REGISTRY_PASSWORD

builder:
  arch:
    - amd64

env:
  clear:
    DB_DIR: /var/db
  secret:
    - ANYMAIL_WEBHOOK_SECRET
    - AWS_ACCESS_KEY_ID
    - AWS_SECRET_ACCESS_KEY
    - MATT_EMAIL_ADDRESS
    - REPLY_TO_ADDRESS
    - REQUIRED_TO_ADDRESS
    - SENTRY_DSN

aliases:
  shell: app exec --interactive --reuse "bash"
  ssh: server exec --interactive "bash"

volumes:
 - "/var/db:/var/db"
