service: journal
image: mblayman/journal

servers:
  web:
    hosts:
      - 178.128.132.8
    proxy:
      app_port: 8000
      host: journeyinbox.com
      ssl: true
      healthcheck:
        # The db migration might make the app take longer to boot up
        # so provide more time before failing the health check.
        timeout: 60
  goweb:
    hosts:
      - 178.128.132.8
    proxy:
      app_port: 8080
      host: beta.journeyinbox.com
      ssl: true
      healthcheck:
        # The db migration might make the app take longer to boot up
        # so provide more time before failing the health check.
        timeout: 60
    cmd:
      /app/app
  worker:
    hosts:
      - 178.128.132.8
    cmd:
      # Don't waste time running the system checks.
      python /app/manage.py run_huey --skip-checks

registry:
  username: mblayman
  password:
    - KAMAL_REGISTRY_PASSWORD

builder:
  arch:
    - amd64

env:
  clear:
    # Ideally, kamal-proxy would pass along a Host header that could be validated.
    # Instead, it relies on the `kamal` Docker network so the Host header
    # contains the container ID of the proxy. As of 2024-10-09, there is no way
    # I can find to pass along the header. Therefore, skip the ALLOWED_HOSTS check.
    ALLOWED_HOSTS: '*'
    DB_DIR: /var/db
    # Make sure we never accidentally set DEBUG to True for production.
    DEBUG: "False"
    PYTHONUNBUFFERED: "1"
  secret:
    - ADMIN_URL_PATH_TOKEN
    - ANYMAIL_WEBHOOK_SECRET
    - HASHID_FIELD_SALT
    - REQUIRED_TO_ADDRESS
    - SECRET_KEY
    - SENDGRID_API_KEY
    - SENTRY_DSN

aliases:
  shell: app exec --interactive --reuse "bash"
  ssh: server exec --interactive "bash"

volumes:
 - "/var/db:/var/db"
