# Generated by Django 4.2.1 on 2023-08-03 02:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_historicalaccount"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="activate_date",
            field=models.DateTimeField(
                blank=True,
                help_text="keep empty for an immediate activation",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="deactivate_date",
            field=models.DateTimeField(
                blank=True, help_text="keep empty for indefinite activation", null=True
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="status",
            field=models.IntegerField(
                choices=[(0, "Inactive"), (1, "Active")],
                default=1,
                verbose_name="status",
            ),
        ),
    ]
