# Generated by Django 4.2.1 on 2023-11-02 01:50

import hashid_field.field
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_user_activate_date_user_deactivate_date_user_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="id",
            field=hashid_field.field.HashidAutoField(
                alphabet="abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890",
                min_length=7,
                prefix="",
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="historicalaccount",
            name="id",
            field=models.IntegerField(blank=True, db_index=True),
        ),
    ]
