# Generated by Django 5.1.4 on 2025-01-31 02:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_alter_account_id_alter_historicalaccount_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="verified",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text=(
                    "An account is verified if they log in through email at least once"
                ),
            ),
        ),
        migrations.AddField(
            model_name="historicalaccount",
            name="verified",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text=(
                    "An account is verified if they log in through email at least once"
                ),
            ),
        ),
    ]
