# Generated by Django 4.2.1 on 2024-03-21 03:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("entries", "0002_prompt"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entry",
            name="when",
            field=models.DateField(db_index=True),
        ),
    ]
