# Generated by Django 5.0.6 on 2024-05-23 01:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("entries", "0003_alter_entry_when"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="entry",
            constraint=models.UniqueConstraint(
                fields=("user", "when"), name="user_per_day"
            ),
        ),
    ]
