name: Tests Runner
on:
  - push

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-22.04
    env:
      ADMIN_URL_PATH_TOKEN: 'token'
      ALLOWED_HOSTS: '*'
      ANYMAIL_WEBHOOK_SECRET: 'random16:random16'
      HASHID_FIELD_SALT: 'somesalt'
      SECRET_KEY: 'a secret to everybody'
      SECURE_SSL_REDIRECT: 'off'
      SENDGRID_API_KEY: 'fake_apikey'
      SENTRY_ENABLED: 'off'
      SENTRY_DSN: 'dsn_example'

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v2

      - name: Set up Python
        run: uv python install

      - name: Install the project
        run: uv sync --dev

      - name: Test it
        run: make coverage

      - name: Check deploy configuration
        run: uv run manage.py check --deploy --fail-level WARNING
        env:
          DATABASE_URL: 'sqlite://:memory:'
          SECRET_KEY: 'zt(6jlr#oquxm2t%ryh#n+-72p^(3knbf&q$5x16#o%1im-s7!'
          SECURE_SSL_REDIRECT: 'on'
